export const PROJECTS_REQUEST = "PROJECT_REQUEST";
export const PROJECTS_SUCCESS = "PROJECT_SUCCESS";
export const PROJECTS_FAILURE = "PROJECT_FAILURE";
export const PROJECT_DELETE = "PROJECT_DELETE";
